guests = ['grandfather','mother','father']
print("Hi " + guests[0].title() + " do you want to go a dinner's family?")
print("Hi " + guests[1].title() + " do you want to go a dinner's family?")
print("Hi " + guests[2].title() + " do you want to go a dinner's family?")
print("Oh, the " +guests[0].title()+ " don't can go to the dinner.")
guests[0] = 'aunt'
print("Hi " + guests[0].title() + " do you want to go a dinner's family?")
print("Hi " + guests[1].title() + " do you want to go a dinner's family?")
print("Hi " + guests[2].title() + " do you want to go a dinner's family?")
print("Hey, i find a large table for this dinner!")
guests.insert(0,'cousin')
guests.insert(0,'uncle')
guests.append('grandmother')
print(guests)
print("Hi " + guests[0].title() + " do you want to go a dinner's family?")
print("Hi " + guests[1].title() + " do you want to go a dinner's family?")
print("Hi " + guests[2].title() + " do you want to go a dinner's family?")
print("Hi " + guests[3].title() + " do you want to go a dinner's family?")
print("Hi " + guests[4].title() + " do you want to go a dinner's family?")
print("Hi " + guests[5].title() + " do you want to go a dinner's family?")
